package org.tuubes.craft.mc1_12_2.play.clientbound

import com.electronwill.niol.{NiolInput, NiolOutput}
import org.tuubes.craft.CraftAttach
import org.tuubes.core.network._
import KeepAlivePacketBuilder._

/** Packet class auto-generated by DataTractor */
final class KeepAlivePacket(var keepAliveId: Long) extends Packet {
  override def write(out: NiolOutput): Unit = {
    out.putLong(keepAliveId)
  }
	
  override def id = KeepAlivePacket.id

	
}
object KeepAlivePacket extends PacketObj[CraftAttach, KeepAlivePacket] {
  override val id = 31
	
  override def read(in: NiolInput): KeepAlivePacket = {
    val keepAliveId = in.getLong()
    new KeepAlivePacket(keepAliveId)
  }
}
/** Packet builder auto-generated by DataTractor */
final class KeepAlivePacketBuilder[P <: KeepAlivePacket] extends PacketBuilder[KeepAlivePacket, P =:= Complete] {
  private[this] var keepAliveId: Long = _

  def withKeepAliveId(keepAliveId: Long): KeepAlivePacketBuilder[P with KeepAliveId] = {
    this.keepAliveId = keepAliveId
    this.asInstanceOf[KeepAlivePacketBuilder[P with KeepAliveId]]
  }

  override def build()(implicit evidence: P =:= Complete) = {
    new KeepAlivePacket(keepAliveId)
  }
}
object KeepAlivePacketBuilder {
  sealed trait KeepAliveId
  type Complete = KeepAlivePacket with KeepAliveId
}
