package org.tuubes.craft.mc1_12_2.handshaking

import org.tuubes.craft.mc1_12_2.handshaking.serverbound._
import org.tuubes.craft.MinecraftProtocol

/** Protocol class auto-generated by DataTractor */
object HandshakingProtocol extends MinecraftProtocol {
  registerPacket(HandshakePacket)
  registerPacket(LegacyServerListPingPacket)
}
