package org.tuubes.craft.mc1_12_2.play.serverbound

import ClientStatusPacketBuilder._
import com.electronwill.niol.{NiolInput, NiolOutput}
import org.tuubes.craft.CraftAttach
import org.tuubes.core.network._

/** Packet class auto-generated by DataTractor */
final class ClientStatusPacket(var actionId: Int) extends Packet {
  override def write(out: NiolOutput): Unit = {
    out.putVarint(actionId)
  }
	
  override def id = ClientStatusPacket.id

	
}
object ClientStatusPacket extends PacketObj[CraftAttach, ClientStatusPacket] {
  override val id = 3
	
  override def read(in: NiolInput): ClientStatusPacket = {
    val actionId = in.getVarint()
    new ClientStatusPacket(actionId)
  }
}
/** Packet builder auto-generated by DataTractor */
final class ClientStatusPacketBuilder[P <: ClientStatusPacket] extends PacketBuilder[ClientStatusPacket, P =:= Complete] {
  private[this] var actionId: Int = _

  def withActionId(actionId: Int): ClientStatusPacketBuilder[P with ActionId] = {
    this.actionId = actionId
    this.asInstanceOf[ClientStatusPacketBuilder[P with ActionId]]
  }

  override def build()(implicit evidence: P =:= Complete) = {
    new ClientStatusPacket(actionId)
  }
}
object ClientStatusPacketBuilder {
  sealed trait ActionId
  type Complete = ClientStatusPacket with ActionId
}
