package org.tuubes.craft.mc1_12_2.play.serverbound

import com.electronwill.niol.{NiolInput, NiolOutput}
import org.tuubes.craft.CraftAttach
import org.tuubes.core.network._
import CraftRecipeRequestPacketBuilder._

/** Packet class auto-generated by DataTractor */
final class CraftRecipeRequestPacket(var windowId: Byte, var recipe: Int, var makeAll: Boolean) extends Packet {
  override def write(out: NiolOutput): Unit = {
    out.putByte(windowId)
    out.putVarint(recipe)
    out.putBool(makeAll)
  }
	
  override def id = CraftRecipeRequestPacket.id

	
}
object CraftRecipeRequestPacket extends PacketObj[CraftAttach, CraftRecipeRequestPacket] {
  override val id = 18
	
  override def read(in: NiolInput): CraftRecipeRequestPacket = {
    val windowId = in.getByte()
    val recipe = in.getVarint()
    val makeAll = in.getBool()
    new CraftRecipeRequestPacket(windowId, recipe, makeAll)
  }
}
/** Packet builder auto-generated by DataTractor */
final class CraftRecipeRequestPacketBuilder[P <: CraftRecipeRequestPacket] extends PacketBuilder[CraftRecipeRequestPacket, P =:= Complete] {
  private[this] var windowId: Byte = _
  private[this] var recipe: Int = _
  private[this] var makeAll: Boolean = _

  def withWindowId(windowId: Byte): CraftRecipeRequestPacketBuilder[P with WindowId] = {
    this.windowId = windowId
    this.asInstanceOf[CraftRecipeRequestPacketBuilder[P with WindowId]]
  }

  def withRecipe(recipe: Int): CraftRecipeRequestPacketBuilder[P with Recipe] = {
    this.recipe = recipe
    this.asInstanceOf[CraftRecipeRequestPacketBuilder[P with Recipe]]
  }

  def withMakeAll(makeAll: Boolean): CraftRecipeRequestPacketBuilder[P with MakeAll] = {
    this.makeAll = makeAll
    this.asInstanceOf[CraftRecipeRequestPacketBuilder[P with MakeAll]]
  }

  override def build()(implicit evidence: P =:= Complete) = {
    new CraftRecipeRequestPacket(windowId, recipe, makeAll)
  }
}
object CraftRecipeRequestPacketBuilder {
  sealed trait WindowId
  sealed trait Recipe
  sealed trait MakeAll
  type Complete = CraftRecipeRequestPacket with WindowId with Recipe with MakeAll
}
