package org.tuubes.craft.mc1_12_2.play.serverbound

import com.electronwill.niol.{NiolInput, NiolOutput}
import org.tuubes.craft.CraftAttach
import org.tuubes.core.network._
import UseItemPacketBuilder._

/** Packet class auto-generated by DataTractor */
final class UseItemPacket(var hand: Int) extends Packet {
  override def write(out: NiolOutput): Unit = {
    out.putVarint(hand)
  }
	
  override def id = UseItemPacket.id

	
}
object UseItemPacket extends PacketObj[CraftAttach, UseItemPacket] {
  override val id = 32
	
  override def read(in: NiolInput): UseItemPacket = {
    val hand = in.getVarint()
    new UseItemPacket(hand)
  }
}
/** Packet builder auto-generated by DataTractor */
final class UseItemPacketBuilder[P <: UseItemPacket] extends PacketBuilder[UseItemPacket, P =:= Complete] {
  private[this] var hand: Int = _

  def withHand(hand: Int): UseItemPacketBuilder[P with Hand] = {
    this.hand = hand
    this.asInstanceOf[UseItemPacketBuilder[P with Hand]]
  }

  override def build()(implicit evidence: P =:= Complete) = {
    new UseItemPacket(hand)
  }
}
object UseItemPacketBuilder {
  sealed trait Hand
  type Complete = UseItemPacket with Hand
}
