package org.tuubes.craft.mc1_12.handshaking

import org.tuubes.core.engine.GameObject
import org.tuubes.craft.MinecraftProtocol
import org.tuubes.craft.mc1_12.handshaking.serverbound._

/** Protocol class auto-generated by DataTractor */
object HandshakingProtocol extends MinecraftProtocol {
  registerPacket(HandshakePacket)

  override def spawn(obj: GameObject): Unit = ???

  override def despawn(obj: GameObject): Unit = ???
}
