package org.tuubes.craft.mc1_12.handshaking.serverbound

import com.electronwill.niol.{NiolInput, NiolOutput}
import org.tuubes.core.network._
import LegacyServerListPingPacketBuilder._
import org.tuubes.craft.CraftAttach

/** Packet class auto-generated by DataTractor */
final class LegacyServerListPingPacket(var payload: Int) extends Packet[CraftAttach] {
  override def write(out: NiolOutput): Unit = {
    out.putInt(payload)
  }
	
  override def obj = LegacyServerListPingPacket
}
object LegacyServerListPingPacket extends PacketObj[CraftAttach, LegacyServerListPingPacket] {
  override val id = 254
	
  override def read(in: NiolInput): LegacyServerListPingPacket = {
    val payload = in.getUnsignedByte()
    new LegacyServerListPingPacket(payload)
  }
}
/** Packet builder auto-generated by DataTractor */
final class LegacyServerListPingPacketBuilder[P <: LegacyServerListPingPacket] extends PacketBuilder[LegacyServerListPingPacket, P =:= Complete] {
  private[this] var payload: Int = _

  def withPayload(payload: Int): LegacyServerListPingPacketBuilder[P with Payload] = {
    this.payload = payload
    this.asInstanceOf[LegacyServerListPingPacketBuilder[P with Payload]]
  }

  override def build()(implicit evidence: P =:= Complete) = {
    new LegacyServerListPingPacket(payload)
  }
}
object LegacyServerListPingPacketBuilder {
  sealed trait Payload
  type Complete = LegacyServerListPingPacket with Payload
}
