package org.tuubes.craft.mc1_12.play.serverbound

import com.electronwill.niol.{NiolInput, NiolOutput}
import org.tuubes.core.network._
import HeldItemChangePacketBuilder._
import org.tuubes.craft.CraftAttach

/** Packet class auto-generated by DataTractor */
final class HeldItemChangePacket(var slot: Short) extends Packet[CraftAttach] {
  override def write(out: NiolOutput): Unit = {
    out.putShort(slot)
  }
	
  override def obj = HeldItemChangePacket

	
}
object HeldItemChangePacket extends PacketObj[CraftAttach, HeldItemChangePacket] {
  override val id = 26
	
  override def read(in: NiolInput): HeldItemChangePacket = {
    val slot = in.getShort()
    new HeldItemChangePacket(slot)
  }
}
/** Packet builder auto-generated by DataTractor */
final class HeldItemChangePacketBuilder[P <: HeldItemChangePacket] extends PacketBuilder[HeldItemChangePacket, P =:= Complete] {
  private[this] var slot: Short = _

  def withSlot(slot: Short): HeldItemChangePacketBuilder[P with Slot] = {
    this.slot = slot
    this.asInstanceOf[HeldItemChangePacketBuilder[P with Slot]]
  }

  override def build()(implicit evidence: P =:= Complete) = {
    new HeldItemChangePacket(slot)
  }
}
object HeldItemChangePacketBuilder {
  sealed trait Slot
  type Complete = HeldItemChangePacket with Slot
}
