package org.tuubes.craft.mc1_12.play.serverbound

import com.electronwill.niol.{NiolInput, NiolOutput}
import org.tuubes.network._

/** Packet class auto-generated by DataTractor */
final class PlayerPacket(var onGround: Boolean) extends Packet {
  override def write(out: NiolOutput): Unit {
    out.putBoolean(onGround)
  }
	
  override def id = PlayerPacket.id

	
}
object PlayerPacket extends PacketObj[PlayerPacket] {
  override val id = 13
	
  override def read(in: NiolOutput): PlayerPacket {
    val onGround = in.getBoolean()
    new PlayerPacket(onGround)
  }
}
/** Packet builder auto-generated by DataTractor */
final class PlayerPacketBuilder[P <: PlayerPacket] extends PacketBuilder[PlayerPacket, Complete] {
  private[this] var onGround: Boolean = _

  def withOnGround(onGround: Boolean): PlayerPacketBuilder[P with OnGround] = {
    this.onGround = onGround
    this.asInstanceOf[PlayerPacketBuilder[P with OnGround]]
  }

  override def build()(implicit evidence: P =:= Complete) {
    new PlayerPacket(onGround)
  }
}
object PlayerPacketBuilder {
  sealed trait OnGround
  type Complete = PlayerPacketBuilder with OnGround
}
