package org.tuubes.craft.mc1_12.play.serverbound

import com.electronwill.niol.{NiolInput, NiolOutput}
import PlayerPositionPacketBuilder._
import org.tuubes.craft.CraftAttach
import org.tuubes.core.network._

/** Packet class auto-generated by DataTractor */
final class PlayerPositionPacket(var x: Double, var feetY: Double, var z: Double, var onGround: Boolean) extends Packet[CraftAttach] {
  override def write(out: NiolOutput): Unit = {
    out.putDouble(x)
    out.putDouble(feetY)
    out.putDouble(z)
    out.putBool(onGround)
  }
	
  override def obj = PlayerPositionPacket

	
}
object PlayerPositionPacket extends PacketObj[CraftAttach, PlayerPositionPacket] {
  override val id = 13
	
  override def read(in: NiolInput): PlayerPositionPacket = {
    val x = in.getDouble()
    val feetY = in.getDouble()
    val z = in.getDouble()
    val onGround = in.getBool()
    new PlayerPositionPacket(x, feetY, z, onGround)
  }
}
/** Packet builder auto-generated by DataTractor */
final class PlayerPositionPacketBuilder[P <: PlayerPositionPacket] extends PacketBuilder[PlayerPositionPacket, P =:= Complete] {
  private[this] var x: Double = _
  private[this] var feetY: Double = _
  private[this] var z: Double = _
  private[this] var onGround: Boolean = _

  def withX(x: Double): PlayerPositionPacketBuilder[P with X] = {
    this.x = x
    this.asInstanceOf[PlayerPositionPacketBuilder[P with X]]
  }

  def withFeetY(feetY: Double): PlayerPositionPacketBuilder[P with FeetY] = {
    this.feetY = feetY
    this.asInstanceOf[PlayerPositionPacketBuilder[P with FeetY]]
  }

  def withZ(z: Double): PlayerPositionPacketBuilder[P with Z] = {
    this.z = z
    this.asInstanceOf[PlayerPositionPacketBuilder[P with Z]]
  }

  def withOnGround(onGround: Boolean): PlayerPositionPacketBuilder[P with OnGround] = {
    this.onGround = onGround
    this.asInstanceOf[PlayerPositionPacketBuilder[P with OnGround]]
  }

  override def build()(implicit evidence: P =:= Complete) = {
    new PlayerPositionPacket(x, feetY, z, onGround)
  }
}
object PlayerPositionPacketBuilder {
  sealed trait X
  sealed trait FeetY
  sealed trait Z
  sealed trait OnGround
  type Complete = PlayerPositionPacket with X with FeetY with Z with OnGround
}
