package org.tuubes.craft.mc1_12.play.serverbound

import com.electronwill.niol.{NiolInput, NiolOutput}
import PlayerAbilitiesPacketBuilder._
import org.tuubes.craft.CraftAttach
import org.tuubes.core.network._

/** Packet class auto-generated by DataTractor */
final class PlayerAbilitiesPacket(var flags: Byte, var flyingSpeed: Float, var walkingSpeed: Float) extends Packet[CraftAttach] {
  override def write(out: NiolOutput): Unit = {
    out.putByte(flags)
    out.putFloat(flyingSpeed)
    out.putFloat(walkingSpeed)
  }
	
  override def obj = PlayerAbilitiesPacket

	
}
object PlayerAbilitiesPacket extends PacketObj[CraftAttach, PlayerAbilitiesPacket] {
  override val id = 19
	
  override def read(in: NiolInput): PlayerAbilitiesPacket = {
    val flags = in.getByte()
    val flyingSpeed = in.getFloat()
    val walkingSpeed = in.getFloat()
    new PlayerAbilitiesPacket(flags, flyingSpeed, walkingSpeed)
  }
}
/** Packet builder auto-generated by DataTractor */
final class PlayerAbilitiesPacketBuilder[P <: PlayerAbilitiesPacket] extends PacketBuilder[PlayerAbilitiesPacket, P =:= Complete] {
  private[this] var flags: Byte = _
  private[this] var flyingSpeed: Float = _
  private[this] var walkingSpeed: Float = _

  def withFlags(flags: Byte): PlayerAbilitiesPacketBuilder[P with Flags] = {
    this.flags = flags
    this.asInstanceOf[PlayerAbilitiesPacketBuilder[P with Flags]]
  }

  def withFlyingSpeed(flyingSpeed: Float): PlayerAbilitiesPacketBuilder[P with FlyingSpeed] = {
    this.flyingSpeed = flyingSpeed
    this.asInstanceOf[PlayerAbilitiesPacketBuilder[P with FlyingSpeed]]
  }

  def withWalkingSpeed(walkingSpeed: Float): PlayerAbilitiesPacketBuilder[P with WalkingSpeed] = {
    this.walkingSpeed = walkingSpeed
    this.asInstanceOf[PlayerAbilitiesPacketBuilder[P with WalkingSpeed]]
  }

  override def build()(implicit evidence: P =:= Complete) = {
    new PlayerAbilitiesPacket(flags, flyingSpeed, walkingSpeed)
  }
}
object PlayerAbilitiesPacketBuilder {
  sealed trait Flags
  sealed trait FlyingSpeed
  sealed trait WalkingSpeed
  type Complete = PlayerAbilitiesPacket with Flags with FlyingSpeed with WalkingSpeed
}
