package org.tuubes.craft.mc1_12_2.status

import org.tuubes.craft.mc1_12_2.status.serverbound._
import org.tuubes.craft.MinecraftProtocol

/** Protocol class auto-generated by DataTractor */
object StatusProtocol extends MinecraftProtocol {
  registerPacket(PingPacket)
  registerPacket(RequestPacket)
}
