package org.tuubes.craft.mc1_12.status.serverbound

import com.electronwill.niol.{NiolInput, NiolOutput}
import org.tuubes.core.network._
import PingPacketBuilder._
import org.tuubes.craft.CraftAttach

/** Packet class auto-generated by DataTractor */
final class PingPacket(var payload: Long) extends Packet[CraftAttach] {
  override def write(out: NiolOutput): Unit = {
    out.putLong(payload)
  }
	
  override def obj = PingPacket

	
}
object PingPacket extends PacketObj[CraftAttach, PingPacket] {
  override val id = 1
	
  override def read(in: NiolInput): PingPacket = {
    val payload = in.getLong()
    new PingPacket(payload)
  }
}
/** Packet builder auto-generated by DataTractor */
final class PingPacketBuilder[P <: PingPacket] extends PacketBuilder[PingPacket, P =:= Complete] {
  private[this] var payload: Long = _

  def withPayload(payload: Long): PingPacketBuilder[P with Payload] = {
    this.payload = payload
    this.asInstanceOf[PingPacketBuilder[P with Payload]]
  }

  override def build()(implicit evidence: P =:= Complete) = {
    new PingPacket(payload)
  }
}
object PingPacketBuilder {
  sealed trait Payload
  type Complete = PingPacket with Payload
}
