package org.tuubes.craft.mc1_12.status.serverbound

import com.electronwill.niol.{NiolInput, NiolOutput}
import org.tuubes.network._

/** Packet class auto-generated by DataTractor */
final class RequestPacket() extends Packet {
  override def write(out: NiolOutput): Unit {

  }
	
  override def id = RequestPacket.id

	
}
object RequestPacket extends PacketObj[RequestPacket] {
  override val id = 0
	
  override def read(in: NiolOutput): RequestPacket {

    new RequestPacket()
  }
}
/** Packet builder auto-generated by DataTractor */
final class RequestPacketBuilder[P <: RequestPacket] extends PacketBuilder[RequestPacket, Complete] {




  override def build()(implicit evidence: P =:= Complete) {
    new RequestPacket()
  }
}
object RequestPacketBuilder {
  
  type Complete = RequestPacketBuilder
}
