package org.tuubes.craft.mc1_12.status.serverbound

import com.electronwill.niol.{NiolInput, NiolOutput}
import org.tuubes.core.network._
import org.tuubes.craft.CraftAttach
import RequestPacketBuilder._

/** Packet class auto-generated by DataTractor */
final class RequestPacket() extends Packet[CraftAttach] {
  override def write(out: NiolOutput): Unit = {

  }
	
  override def obj = RequestPacket

	
}
object RequestPacket extends PacketObj[CraftAttach, RequestPacket] {
  override val id = 0
	
  override def read(in: NiolInput): RequestPacket = {

    new RequestPacket()
  }
}
/** Packet builder auto-generated by DataTractor */
final class RequestPacketBuilder[P <: RequestPacket] extends PacketBuilder[RequestPacket, P =:= Complete] {




  override def build()(implicit evidence: P =:= Complete) = {
    new RequestPacket()
  }
}
object RequestPacketBuilder {
  
  type Complete = RequestPacket
}
