package org.tuubes.craft.mc1_12.play.clientbound

import org.tuubes.network._
import com.electronwill.niol.{NiolInput, NiolOutput}

/** Packet class auto-generated by DataTractor */
final class CameraPacket(var cameraId: Int) extends Packet {
  override def write(out: NiolOutput): Unit = {
    out.putVarint(cameraId)
  }
	
  override def obj = CameraPacket

	
}
object CameraPacket extends PacketObj[CameraPacket] {
  override val id = 56
	
  override def read(in: NiolOutput): CameraPacket = {
    val cameraId = in.getVarint()
    new CameraPacket(cameraId)
  }
}
/** Packet builder auto-generated by DataTractor */
final class CameraPacketBuilder[P <: CameraPacket] extends PacketBuilder[CameraPacket, Complete] {
  private[this] var cameraId: Int = _

  def withCameraId(cameraId: Int): CameraPacketBuilder[P with CameraId] = {
    this.cameraId = cameraId
    this.asInstanceOf[CameraPacketBuilder[P with CameraId]]
  }

  override def build()(implicit evidence: P =:= Complete) = {
    new CameraPacket(cameraId)
  }
}
object CameraPacketBuilder {
  sealed trait CameraId
  type Complete = CameraPacketBuilder with CameraId
}
