package org.tuubes.craft.mc1_12.play.clientbound

import com.electronwill.niol.{NiolInput, NiolOutput}
import org.tuubes.core.network._
import DestroyEntitiesPacketBuilder._
import org.tuubes.craft.CraftAttach

/** Packet class auto-generated by DataTractor */
final class DestroyEntitiesPacket(var entityIds: Array[Int]) extends Packet[CraftAttach] {
  override def write(out: NiolOutput): Unit = {
    out.putVarint(entityIds.length)
    var i_entityIds = 0
    while (i_entityIds < entityIds.length) {
      out.putVarint(entityIds(i_entityIds))
      i_entityIds += 1
    }
  }
	
  override def obj = DestroyEntitiesPacket

	
}
object DestroyEntitiesPacket extends PacketObj[CraftAttach, DestroyEntitiesPacket] {
  override val id = 49
	
  override def read(in: NiolInput): DestroyEntitiesPacket = {
    val entityIdsLength = in.getVarint()
    var i_entityIds = 0
    val entityIds = new Array[Int](entityIdsLength)
    while (i_entityIds < entityIdsLength) {
      entityIds(i_entityIds) = in.getVarint()
      i_entityIds += 1
    }
    new DestroyEntitiesPacket(entityIds)
  }
}
/** Packet builder auto-generated by DataTractor */
final class DestroyEntitiesPacketBuilder[P <: DestroyEntitiesPacket] extends PacketBuilder[DestroyEntitiesPacket, P =:= Complete] {
  private[this] var entityIds: Array[Int] = _

  def withEntityIds(entityIds: Array[Int]): DestroyEntitiesPacketBuilder[P with EntityIds] = {
    this.entityIds = entityIds
    this.asInstanceOf[DestroyEntitiesPacketBuilder[P with EntityIds]]
  }

  override def build()(implicit evidence: P =:= Complete) = {
    new DestroyEntitiesPacket(entityIds)
  }
}
object DestroyEntitiesPacketBuilder {
  sealed trait EntityIds
  type Complete = DestroyEntitiesPacket with EntityIds
}
