package org.tuubes.craft.mc1_12.play.clientbound

import com.electronwill.niol.{NiolInput, NiolOutput}
import org.tuubes.network._

/** Packet class auto-generated by DataTractor */
final class EntityPacket(var entityId: Int) extends Packet {
  override def write(out: NiolOutput): Unit {
    out.putVarint(entityId)
  }
	
  override def id = EntityPacket.id

	
}
object EntityPacket extends PacketObj[EntityPacket] {
  override val id = 37
	
  override def read(in: NiolOutput): EntityPacket {
    val entityId = in.getVarint()
    new EntityPacket(entityId)
  }
}
/** Packet builder auto-generated by DataTractor */
final class EntityPacketBuilder[P <: EntityPacket] extends PacketBuilder[EntityPacket, Complete] {
  private[this] var entityId: Int = _

  def withEntityId(entityId: Int): EntityPacketBuilder[P with EntityId] = {
    this.entityId = entityId
    this.asInstanceOf[EntityPacketBuilder[P with EntityId]]
  }

  override def build()(implicit evidence: P =:= Complete) {
    new EntityPacket(entityId)
  }
}
object EntityPacketBuilder {
  sealed trait EntityId
  type Complete = EntityPacketBuilder with EntityId
}
