package org.tuubes.craft.mc1_12.play.clientbound

import com.electronwill.niol.{NiolInput, NiolOutput}
import org.tuubes.network._

/** Packet class auto-generated by DataTractor */
final class HeldItemChangePacket(var slot: Byte) extends Packet {
  override def write(out: NiolOutput): Unit {
    out.putByte(slot)
  }
	
  override def id = HeldItemChangePacket.id

	
}
object HeldItemChangePacket extends PacketObj[HeldItemChangePacket] {
  override val id = 57
	
  override def read(in: NiolOutput): HeldItemChangePacket {
    val slot = in.getByte()
    new HeldItemChangePacket(slot)
  }
}
/** Packet builder auto-generated by DataTractor */
final class HeldItemChangePacketBuilder[P <: HeldItemChangePacket] extends PacketBuilder[HeldItemChangePacket, Complete] {
  private[this] var slot: Byte = _

  def withSlot(slot: Byte): HeldItemChangePacketBuilder[P with Slot] = {
    this.slot = slot
    this.asInstanceOf[HeldItemChangePacketBuilder[P with Slot]]
  }

  override def build()(implicit evidence: P =:= Complete) {
    new HeldItemChangePacket(slot)
  }
}
object HeldItemChangePacketBuilder {
  sealed trait Slot
  type Complete = HeldItemChangePacketBuilder with Slot
}
