package org.tuubes.craft.mc1_12.play.clientbound

import java.nio.charset.StandardCharsets.UTF_8
import com.electronwill.niol.{NiolInput, NiolOutput}
import org.tuubes.network._

/** Packet class auto-generated by DataTractor */
final class SelectAdvancementTabPacket(var hasId: Boolean, var optionalIdentifier: String) extends Packet {
  override def write(out: NiolOutput): Unit = {
    out.putBoolean(hasId)
    out.putVarstring(optionalIdentifier, UTF_8)
  }
	
  override def obj = SelectAdvancementTabPacket

	
}
object SelectAdvancementTabPacket extends PacketObj[SelectAdvancementTabPacket] {
  override val id = 54
	
  override def read(in: NiolOutput): SelectAdvancementTabPacket = {
    val hasId = in.getBoolean()
    val optionalIdentifier = in.getVarstring(UTF_8)
    new SelectAdvancementTabPacket(hasId, optionalIdentifier)
  }
}
/** Packet builder auto-generated by DataTractor */
final class SelectAdvancementTabPacketBuilder[P <: SelectAdvancementTabPacket] extends PacketBuilder[SelectAdvancementTabPacket, Complete] {
  private[this] var hasId: Boolean = _
  private[this] var optionalIdentifier: String = _

  def withHasId(hasId: Boolean): SelectAdvancementTabPacketBuilder[P with HasId] = {
    this.hasId = hasId
    this.asInstanceOf[SelectAdvancementTabPacketBuilder[P with HasId]]
  }

  def withOptionalIdentifier(optionalIdentifier: String): SelectAdvancementTabPacketBuilder[P with OptionalIdentifier] = {
    this.optionalIdentifier = optionalIdentifier
    this.asInstanceOf[SelectAdvancementTabPacketBuilder[P with OptionalIdentifier]]
  }

  override def build()(implicit evidence: P =:= Complete) = {
    new SelectAdvancementTabPacket(hasId, optionalIdentifier)
  }
}
object SelectAdvancementTabPacketBuilder {
  sealed trait HasId
  sealed trait OptionalIdentifier
  type Complete = SelectAdvancementTabPacketBuilder with HasId with OptionalIdentifier
}
