package org.tuubes.craft.mc1_12.play.clientbound

import com.electronwill.niol.{NiolInput, NiolOutput}
import org.tuubes.network._

/** Packet class auto-generated by DataTractor */
final class ServerDifficultyPacket(var difficulty: Int) extends Packet {
  override def write(out: NiolOutput): Unit {
    out.putInt(difficulty)
  }
	
  override def id = ServerDifficultyPacket.id

	
}
object ServerDifficultyPacket extends PacketObj[ServerDifficultyPacket] {
  override val id = 13
	
  override def read(in: NiolOutput): ServerDifficultyPacket {
    val difficulty = in.getUnsignedByte()
    new ServerDifficultyPacket(difficulty)
  }
}
/** Packet builder auto-generated by DataTractor */
final class ServerDifficultyPacketBuilder[P <: ServerDifficultyPacket] extends PacketBuilder[ServerDifficultyPacket, Complete] {
  private[this] var difficulty: Int = _

  def withDifficulty(difficulty: Int): ServerDifficultyPacketBuilder[P with Difficulty] = {
    this.difficulty = difficulty
    this.asInstanceOf[ServerDifficultyPacketBuilder[P with Difficulty]]
  }

  override def build()(implicit evidence: P =:= Complete) {
    new ServerDifficultyPacket(difficulty)
  }
}
object ServerDifficultyPacketBuilder {
  sealed trait Difficulty
  type Complete = ServerDifficultyPacketBuilder with Difficulty
}
