package org.tuubes.craft.mc1_12.play.clientbound

import com.electronwill.niol.{NiolInput, NiolOutput}
import org.tuubes.network._

/** Packet class auto-generated by DataTractor */
final class SetCooldownPacket(var itemId: Int, var cooldownTicks: Int) extends Packet {
  override def write(out: NiolOutput): Unit {
    out.putVarint(itemId)
    out.putVarint(cooldownTicks)
  }
	
  override def id = SetCooldownPacket.id

	
}
object SetCooldownPacket extends PacketObj[SetCooldownPacket] {
  override val id = 23
	
  override def read(in: NiolOutput): SetCooldownPacket {
    val itemId = in.getVarint()
    val cooldownTicks = in.getVarint()
    new SetCooldownPacket(itemId, cooldownTicks)
  }
}
/** Packet builder auto-generated by DataTractor */
final class SetCooldownPacketBuilder[P <: SetCooldownPacket] extends PacketBuilder[SetCooldownPacket, Complete] {
  private[this] var itemId: Int = _
  private[this] var cooldownTicks: Int = _

  def withItemId(itemId: Int): SetCooldownPacketBuilder[P with ItemId] = {
    this.itemId = itemId
    this.asInstanceOf[SetCooldownPacketBuilder[P with ItemId]]
  }

  def withCooldownTicks(cooldownTicks: Int): SetCooldownPacketBuilder[P with CooldownTicks] = {
    this.cooldownTicks = cooldownTicks
    this.asInstanceOf[SetCooldownPacketBuilder[P with CooldownTicks]]
  }

  override def build()(implicit evidence: P =:= Complete) {
    new SetCooldownPacket(itemId, cooldownTicks)
  }
}
object SetCooldownPacketBuilder {
  sealed trait ItemId
  sealed trait CooldownTicks
  type Complete = SetCooldownPacketBuilder with ItemId with CooldownTicks
}
