package org.tuubes.craft.mc1_12.play.clientbound

import com.electronwill.niol.{NiolInput, NiolOutput}
import org.tuubes.network._

/** Packet class auto-generated by DataTractor */
final class SetExperiencePacket(var experienceBar: Float, var level: Int, var totalExperience: Int) extends Packet {
  override def write(out: NiolOutput): Unit {
    out.putFloat(experienceBar)
    out.putVarint(level)
    out.putVarint(totalExperience)
  }
	
  override def id = SetExperiencePacket.id

	
}
object SetExperiencePacket extends PacketObj[SetExperiencePacket] {
  override val id = 63
	
  override def read(in: NiolOutput): SetExperiencePacket {
    val experienceBar = in.getFloat()
    val level = in.getVarint()
    val totalExperience = in.getVarint()
    new SetExperiencePacket(experienceBar, level, totalExperience)
  }
}
/** Packet builder auto-generated by DataTractor */
final class SetExperiencePacketBuilder[P <: SetExperiencePacket] extends PacketBuilder[SetExperiencePacket, Complete] {
  private[this] var experienceBar: Float = _
  private[this] var level: Int = _
  private[this] var totalExperience: Int = _

  def withExperienceBar(experienceBar: Float): SetExperiencePacketBuilder[P with ExperienceBar] = {
    this.experienceBar = experienceBar
    this.asInstanceOf[SetExperiencePacketBuilder[P with ExperienceBar]]
  }

  def withLevel(level: Int): SetExperiencePacketBuilder[P with Level] = {
    this.level = level
    this.asInstanceOf[SetExperiencePacketBuilder[P with Level]]
  }

  def withTotalExperience(totalExperience: Int): SetExperiencePacketBuilder[P with TotalExperience] = {
    this.totalExperience = totalExperience
    this.asInstanceOf[SetExperiencePacketBuilder[P with TotalExperience]]
  }

  override def build()(implicit evidence: P =:= Complete) {
    new SetExperiencePacket(experienceBar, level, totalExperience)
  }
}
object SetExperiencePacketBuilder {
  sealed trait ExperienceBar
  sealed trait Level
  sealed trait TotalExperience
  type Complete = SetExperiencePacketBuilder with ExperienceBar with Level with TotalExperience
}
