package org.tuubes.craft.mc1_12.play.clientbound

import com.electronwill.niol.{NiolInput, NiolOutput}
import org.tuubes.core.network._
import SoundEffectPacketBuilder._
import org.tuubes.craft.CraftAttach

/** Packet class auto-generated by DataTractor */
final class SoundEffectPacket(var soundId: Int, var soundCategory: Int, var effectPositionX: Int, var effectPositionY: Int, var effectPositionZ: Int, var volume: Float, var pitch: Float) extends Packet[CraftAttach] {
  override def write(out: NiolOutput): Unit = {
    out.putVarint(soundId)
    out.putVarint(soundCategory)
    out.putInt(effectPositionX)
    out.putInt(effectPositionY)
    out.putInt(effectPositionZ)
    out.putFloat(volume)
    out.putFloat(pitch)
  }
	
  override def obj = SoundEffectPacket

	
}
object SoundEffectPacket extends PacketObj[CraftAttach, SoundEffectPacket] {
  override val id = 72
	
  override def read(in: NiolInput): SoundEffectPacket = {
    val soundId = in.getVarint()
    val soundCategory = in.getVarint()
    val effectPositionX = in.getInt()
    val effectPositionY = in.getInt()
    val effectPositionZ = in.getInt()
    val volume = in.getFloat()
    val pitch = in.getFloat()
    new SoundEffectPacket(soundId, soundCategory, effectPositionX, effectPositionY, effectPositionZ, volume, pitch)
  }
}
/** Packet builder auto-generated by DataTractor */
final class SoundEffectPacketBuilder[P <: SoundEffectPacket] extends PacketBuilder[SoundEffectPacket, P =:= Complete] {
  private[this] var soundId: Int = _
  private[this] var soundCategory: Int = _
  private[this] var effectPositionX: Int = _
  private[this] var effectPositionY: Int = _
  private[this] var effectPositionZ: Int = _
  private[this] var volume: Float = _
  private[this] var pitch: Float = _

  def withSoundId(soundId: Int): SoundEffectPacketBuilder[P with SoundId] = {
    this.soundId = soundId
    this.asInstanceOf[SoundEffectPacketBuilder[P with SoundId]]
  }

  def withSoundCategory(soundCategory: Int): SoundEffectPacketBuilder[P with SoundCategory] = {
    this.soundCategory = soundCategory
    this.asInstanceOf[SoundEffectPacketBuilder[P with SoundCategory]]
  }

  def withEffectPositionX(effectPositionX: Int): SoundEffectPacketBuilder[P with EffectPositionX] = {
    this.effectPositionX = effectPositionX
    this.asInstanceOf[SoundEffectPacketBuilder[P with EffectPositionX]]
  }

  def withEffectPositionY(effectPositionY: Int): SoundEffectPacketBuilder[P with EffectPositionY] = {
    this.effectPositionY = effectPositionY
    this.asInstanceOf[SoundEffectPacketBuilder[P with EffectPositionY]]
  }

  def withEffectPositionZ(effectPositionZ: Int): SoundEffectPacketBuilder[P with EffectPositionZ] = {
    this.effectPositionZ = effectPositionZ
    this.asInstanceOf[SoundEffectPacketBuilder[P with EffectPositionZ]]
  }

  def withVolume(volume: Float): SoundEffectPacketBuilder[P with Volume] = {
    this.volume = volume
    this.asInstanceOf[SoundEffectPacketBuilder[P with Volume]]
  }

  def withPitch(pitch: Float): SoundEffectPacketBuilder[P with Pitch] = {
    this.pitch = pitch
    this.asInstanceOf[SoundEffectPacketBuilder[P with Pitch]]
  }

  override def build()(implicit evidence: P =:= Complete) = {
    new SoundEffectPacket(soundId, soundCategory, effectPositionX, effectPositionY, effectPositionZ, volume, pitch)
  }
}
object SoundEffectPacketBuilder {
  sealed trait SoundId
  sealed trait SoundCategory
  sealed trait EffectPositionX
  sealed trait EffectPositionY
  sealed trait EffectPositionZ
  sealed trait Volume
  sealed trait Pitch
  type Complete = SoundEffectPacket with SoundId with SoundCategory with EffectPositionX with EffectPositionY with EffectPositionZ with Volume with Pitch
}
