package org.tuubes.craft.mc1_12.play.clientbound

import UseBedPacketBuilder._
import com.electronwill.utils.Vec3i
import com.electronwill.niol.{NiolInput, NiolOutput}
import org.tuubes.core.network._
import org.tuubes.craft.CraftAttach

/** Packet class auto-generated by DataTractor */
final class UseBedPacket(var entityId: Int, var location: Long) extends Packet[CraftAttach] {
  override def write(out: NiolOutput): Unit = {
    out.putVarint(entityId)
    out.putLong(location)
  }
	
  override def obj = UseBedPacket

  def vecLocation: Vec3i = {
    val x = location >> 38
    val y = (location >> 26) & 0xfff
    val z = location << 38 >> 38
    new Vec3i(x, y, z)
  }	
}
object UseBedPacket extends PacketObj[CraftAttach, UseBedPacket] {
  override val id = 48
	
  override def read(in: NiolInput): UseBedPacket = {
    val entityId = in.getVarint()
    val location = in.getLong()
    new UseBedPacket(entityId, location)
  }
}
/** Packet builder auto-generated by DataTractor */
final class UseBedPacketBuilder[P <: UseBedPacket] extends PacketBuilder[UseBedPacket, P =:= Complete] {
  private[this] var entityId: Int = _
  private[this] var location: Long = _

  def withEntityId(entityId: Int): UseBedPacketBuilder[P with EntityId] = {
    this.entityId = entityId
    this.asInstanceOf[UseBedPacketBuilder[P with EntityId]]
  }

  def withLocation(location: Long): UseBedPacketBuilder[P with Location] = {
    this.location = location
    this.asInstanceOf[UseBedPacketBuilder[P with Location]]
  }

  def withLocation(v: Vec3i): UseBedPacketBuilder[P with Location] = {
    this.location = ((v.x & 0x3ffffff) << 38) | ((v.y & 0xfff) << 26) | (v.z & 0x3ffffff)
    this.asInstanceOf[UseBedPacketBuilder[P with Location]]
  }

  override def build()(implicit evidence: P =:= Complete) = {
    new UseBedPacket(entityId, location)
  }
}
object UseBedPacketBuilder {
  sealed trait EntityId
  sealed trait Location
  type Complete = UseBedPacket with EntityId with Location
}
