package org.tuubes.craft.mc1_12_2.login

import org.tuubes.craft.mc1_12_2.login.serverbound._
import org.tuubes.craft.MinecraftProtocol

/** Protocol class auto-generated by DataTractor */
object LoginProtocol extends MinecraftProtocol {
  registerPacket(EncryptionResponsePacket)
  registerPacket(LoginStartPacket)
}
