package org.tuubes.craft.mc1_12.login.clientbound

import com.electronwill.niol.{NiolInput, NiolOutput}
import java.nio.charset.StandardCharsets.UTF_8
import org.tuubes.network._

/** Packet class auto-generated by DataTractor */
final class DisconnectPacket(var reason: String) extends Packet {
  override def write(out: NiolOutput): Unit {
    out.putVarstring(reason, UTF_8)
  }
	
  override def id = DisconnectPacket.id

	
}
object DisconnectPacket extends PacketObj[DisconnectPacket] {
  override val id = 0
	
  override def read(in: NiolOutput): DisconnectPacket {
    val reason = in.getVarstring(UTF_8)
    new DisconnectPacket(reason)
  }
}
/** Packet builder auto-generated by DataTractor */
final class DisconnectPacketBuilder[P <: DisconnectPacket] extends PacketBuilder[DisconnectPacket, Complete] {
  private[this] var reason: String = _

  def withReason(reason: String): DisconnectPacketBuilder[P with Reason] = {
    this.reason = reason
    this.asInstanceOf[DisconnectPacketBuilder[P with Reason]]
  }

  override def build()(implicit evidence: P =:= Complete) {
    new DisconnectPacket(reason)
  }
}
object DisconnectPacketBuilder {
  sealed trait Reason
  type Complete = DisconnectPacketBuilder with Reason
}
