package org.tuubes.craft.mc1_12_2.play.serverbound

import com.electronwill.niol.{NiolInput, NiolOutput}
import org.tuubes.craft.CraftAttach
import org.tuubes.core.network._
import PlayerPacketBuilder._

/** Packet class auto-generated by DataTractor */
final class PlayerPacket(var onGround: Boolean) extends Packet {
  override def write(out: NiolOutput): Unit = {
    out.putBool(onGround)
  }
	
  override def id = PlayerPacket.id

	
}
object PlayerPacket extends PacketObj[CraftAttach, PlayerPacket] {
  override val id = 12
	
  override def read(in: NiolInput): PlayerPacket = {
    val onGround = in.getBool()
    new PlayerPacket(onGround)
  }
}
/** Packet builder auto-generated by DataTractor */
final class PlayerPacketBuilder[P <: PlayerPacket] extends PacketBuilder[PlayerPacket, P =:= Complete] {
  private[this] var onGround: Boolean = _

  def withOnGround(onGround: Boolean): PlayerPacketBuilder[P with OnGround] = {
    this.onGround = onGround
    this.asInstanceOf[PlayerPacketBuilder[P with OnGround]]
  }

  override def build()(implicit evidence: P =:= Complete) = {
    new PlayerPacket(onGround)
  }
}
object PlayerPacketBuilder {
  sealed trait OnGround
  type Complete = PlayerPacket with OnGround
}
